/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.logina;

import java.awt.event.ActionEvent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maynor
 */
public class ConsulAlumCursos extends javax.swing.JFrame {

    /**
     * Creates new form ConsulAlumCursos
     */
    public ConsulAlumCursos() {
        initComponents();

        ActualizarTabla();
        selector();
    }

    private void ActualizarTabla() {
        DefaultTableModel data = new DefaultTableModel(new String[]{"ID", "Nombre", "Seccion", "Fecha Inicio", "Fecha Fin", "Hora Inicio",
            "Hora Fin", "Profesor", "Nota"}, LoginA.curso.size());
        jTable1.setModel(data);

        int row = 0;
        double totalNotas = 0;
        int contadorNotas = 0;

        for (Cursos c : LoginA.curso) {

            for (Alumno a : c.Alumnos) {
                if (a.carne.equals(LoginA.alumnoLogeado.carne)) {
                    jTable1.setValueAt(c.id, row, 0);
                    jTable1.setValueAt(c.nombre, row, 1);
                    jTable1.setValueAt(c.seccion, row, 2);
                    jTable1.setValueAt(c.fechainicio, row, 3);
                    jTable1.setValueAt(c.fechafin, row, 4);
                    jTable1.setValueAt(c.horaInicio, row, 5);
                    jTable1.setValueAt(c.horaFin, row, 6);
                    jTable1.setValueAt(c.profesor, row, 7);
                    jTable1.setValueAt(a.nota, row, 8);

                    // Acumular notas y contar
                    totalNotas += Double.valueOf(a.nota);
                    contadorNotas++;
                    row++;
                }
            }

        }
        
        this.promedio.setText("Promedio: " + totalNotas / contadorNotas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        promedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        promedio.setText("Promedio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(promedio)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(promedio))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void selector() {
        JMenuItem Desasignar = new JMenuItem("Desasignar");
        Desasignar.addActionListener((ActionEvent e) -> {
            Cursos cursoSeleccionado = LoginA.curso.get(jTable1.getSelectedRow()); // Obtén el curso seleccionado
            cursoSeleccionado.Alumnos.remove(LoginA.alumnoLogeado); // Elimina al alumno de la lista de alumnos del curso seleccionado
            ActualizarTabla();
            JOptionPane.showMessageDialog(this, "Desasignación exitosa.");
        });

        jTable1.setComponentPopupMenu(new JPopupMenu());
        jTable1.getComponentPopupMenu().add(Desasignar);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BienvenidaAlumno a = new BienvenidaAlumno();
        a.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel promedio;
    // End of variables declaration//GEN-END:variables
}
